#! /bin/bash
echo compiling...
g++ $1 uberengine.cpp \
    -o game.o \
    -DDEBUG \
    -O0 \
    $(sdl2-config --libs --cflags) \
    -lSDL2_image \
    -lSDL2_ttf \
    -lSDL2_mixer \
    -lBox2D \
   && ./game.o
